### ISSUE TITLE
Love the tool,  have a small issue

### ISSUE THREAD

**Issue by VileAce** [thomasloupe/Slackord#1]
The error I received is below,  I'm assuming that the message can not be more than 2000 words?

13:50:54 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.ArgumentException: Message content is too long, length must be less or equal to 2000.
Parameter name: Content
   at Discord.API.DiscordRestApiClient.<CreateMessageAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.ChannelHelper.<SendMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Slackord.Slackord.<MessageReceived>d__23.MoveNext() in C:\Users\acid_rain\Desktop\Slackord\Slackord\Slackord\Slackord.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__132.MoveNext()

**Comment by thomasloupe** [comment]
Hi @VileAce,

That is correct. Discord limits _all_ messages to 2000 chars or less, hence the "Message content is too long, length must be less or equal to 2000."

In theory, I could add a concatenation event to messages that are longer than 2000 chars, but I have avoided this as it gives spammers incentive to use the application. I am curious if the application fails to post the rest of the data if it encounters a message over 2000 chars. Are you able to test this and let me know?

Thanks!

**Comment by VileAce** [comment]
When the error occurs, it stops the import completely. I have to the search the json to find the message it failed on split the message and trim all the messages that did import . To me at a minimum it would be nice to receive a warning during the initial loading of the json. That way it would not do a partial import.

**Comment by thomasloupe** [comment]
Hi @VileAce,

That's understandable. I'll see what I can do about that issue.

**Comment by thomasloupe** [comment]
Hi @VileAce,

I have put out [v2.0.5 of Slackord](https://github.com/thomasloupe/Slackord2/releases/tag/v2.0.5) which addresses this issue and adds some additional small QoL changes. Thanks for your reports and suggestions. Happy Slackording!
