### ISSUE TITLE
Hidden files throw NullReferenceException

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#23]
Looks like the script isn't handling "hidden_by_limit" files.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Slackord.Slackord.SelectFileAndConvertJson() in Z:\Development\Git Repositories\Slackord2\Slackord_Win\Slackord\Slackord.cs:line 102
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

```
The file structure looks like this for those:
```
"files": [
    {
        "id": "F031VB5A6CA",
        "mode": "hidden_by_limit"
    }
]
```

**Comment by thomasloupe** [comment]
This looks like a tombstoned file that was over the free tier's filesize limit. I will fix the error handling for this.

**Comment by thomasloupe** [comment]
Fixed: https://github.com/thomasloupe/Slackord2/commit/a3a69c738b1f8935d19c439f1d5b9fa1bde93693
