### ISSUE TITLE
SlashCommandExecuted TimeoutException

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#28]
Not sure what's going on here but I just booted up v2.2.4 and the new slash command failed with this error.
```
16:40:54 Gateway     A SlashCommandExecuted handler has thrown an unhandled exception.:
System.TimeoutException: Cannot respond to an interaction after 3 seconds!
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Slackord.Slackord.SlashCommandHandler(SocketSlashCommand command) in Z:\Development\Git Repositories\Slackord2\Slackord_Win\Slackord\Slackord.cs:line 267
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by thomasloupe** [comment]
It looks like the bot tried to do `AsyncRespond` and failed to do so within 3 seconds. Did retrying fix the issue?
This could've been due to a network issue.

**Comment by jarommadsen** [comment]
I was trying on mobile data (5G though. Seemed pretty strong) but I can give it another go now that I'm on my home network. Reverted to v2.2.3 worked fine though with the !slackord command

**Comment by thomasloupe** [comment]
I can just remove the `AsyncRespond` from the method since it doesn't require a response.

**Comment by thomasloupe** [comment]
Resolved: https://github.com/thomasloupe/Slackord2/commit/a61b8e509c6542d6314e04954ca50a81c51fd2a9.
Feel free to grab the latest build.

**Comment by jarommadsen** [comment]
It did work on my home network on v2.2.4 so probably was just slow network.
