### ISSUE TITLE
Hard crash on Mac importing JSON (from slackdump)

### ISSUE THREAD

**Issue by vertis** [thomasloupe/Slackord#94]
**Slackord version (please complete the following information):**
 - OS: Mac
 - Version: 4.2.3

**Describe the bug**
Hard crash on importing JSON

**To Reproduce**
1. Bot Token
2. Connect
3. Select JSON folder

It gets mid way through parsing the output and then the app has a segfault.
```
2024-02-16 15:08:10.199 Slackord[46645:43995892] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2024-02-16 15:08:20.184 Slackord[46645:43995892] +[CATransaction synchronize] called within transaction
2024-02-16 15:08:28.412 Slackord[46645:43995892] *** Terminating app due to uncaught exception 'System.ArgumentNullException', reason: 'Value cannot be null. (Parameter 'fromPosition') (System.ArgumentNullException)
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 28
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:line 42
   at UIKit.UITextView.GetTextRange(UITextPosition fromPosition, UITextPosition toPosition) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/maccatalyst/generated-sources/UIKit/UITextView.g.cs:line 537
   at Microsoft.Maui.Platform.TextInputExtensions.SetTextRange(IUITextInput platformView, Int32 start, Int32 selectedTextLength)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(IUITextInput textInput, InputView inputView, Boolean isEditing)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(UITextView textView, InputView inputView)
   at Microsoft.Maui.Controls.Editor.MapText(IEditorHandler handler, Editor editor)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(IEditorHandler h, Editor v, Action`2 p)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IEditor, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.InputView.set_Text(String value)
   at MenuApp.ApplicationWindow.PushDebugText() in /Users/thomasloupe/Documents/GitHub/Slackord/Slackord/Classes/ApplicationWindow.cs:line 323
   at MenuApp.ApplicationWindow.WriteToDebugWindow(String text) in /Users/thomasloupe/Documents/GitHub/Slackord/Slackord/Classes/ApplicationWindow.cs:line 312
   at Slackord.Classes.ImportJson.<>c__DisplayClass9_1.<ConvertAsync>b__3() in /Users/thomasloupe/Documents/GitHub/Slackord/Slackord/Classes/ImportJson.cs:line 90
   at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0()
   at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreFoundation/Dispatch.cs:line 379
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at Slackord.Program.Main(String[] args) in /Users/thomasloupe/Documents/GitHub/Slackord/Slackord/Platforms/MacCatalyst/Program.cs:line 12
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001868b70e4 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001863d5fd0 objc_exception_throw + 60
	2   Slackord                            0x0000000100d532d8 xamarin_process_managed_exception + 1052
	3   Slackord                            0x0000000100d52e00 xamarin_process_managed_exception_gchandle + 68
	4   Slackord                            0x0000000100d52db0 xamarin_ftnptr_exception_handler + 24
	5   Slackord                            0x00000001010bfaf8 mono_handle_exception_internal + 5260
	6   Slackord                            0x00000001010be660 mono_handle_exception + 44
	7   Slackord                            0x00000001011175c0 interp_throw + 160
	8   Slackord                            0x00000001011157f0 interp_throw_ex_general + 156
	9   Slackord                            0x00000001011107d8 mono_interp_exec_method + 25196
	10  Slackord                            0x00000001011082d8 interp_entry_from_trampoline + 564
	11  Slackord                            0x0000000100d25938 native_to_interp_trampoline + 104
	12  libdispatch.dylib                   0x00000001865b0400 _dispatch_client_callout + 20
	13  libdispatch.dylib                   0x00000001865bebf8 _dispatch_main_queue_drain + 928
	14  libdispatch.dylib                   0x00000001865be848 _dispatch_main_queue_callback_4CF + 44
	15  CoreFoundation                      0x000000018687fbc4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
	16  CoreFoundation                      0x000000018683d344 __CFRunLoopRun + 1992
	17  CoreFoundation                      0x000000018683c428 CFRunLoopRunSpecific + 612
	18  HIToolbox                           0x0000000190090df0 RunCurrentEventLoopInMode + 292
	19  HIToolbox                           0x0000000190090c2c ReceiveNextEventCommon + 648
	20  HIToolbox                           0x0000000190090984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
	21  AppKit                              0x0000000189a64908 _DPSNextEvent + 636
	22  AppKit                              0x0000000189a63aa4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
	23  AppKit                              0x0000000189a57f08 -[NSApplication run] + 464
	24  AppKit                              0x0000000189a2f358 NSApplicationMain + 880
	25  AppKit                              0x0000000189c87b04 +[NSWindow _savedFrameFromString:] + 0
	26  UIKitMacHelper                      0x000000019deb8960 UINSApplicationMain + 988
	27  UIKitCore                           0x00000001b20278e8 UIApplicationMain + 148
	28  Slackord                            0x0000000100d3c5f4 xamarin_UIApplicationMain + 60
	29  Slackord                            0x0000000101117da0 do_icall + 316
	30  Slackord                            0x0000000101116624 do_icall_wrapper + 356
	31  Slackord                            0x000000010110b04c mono_interp_exec_method + 2784
	32  Slackord                            0x0000000101108c20 interp_runtime_invoke + 244
	33  Slackord                            0x0000000101051490 mono_jit_runtime_invoke + 1140
	34  Slackord                            0x0000000100ff1c70 mono_runtime_invoke_checked + 148
	35  Slackord                            0x0000000100ff7fac mono_runtime_exec_main_checked + 116
	36  Slackord                            0x00000001010a3f48 mono_jit_exec + 364
	37  Slackord                            0x0000000100d65970 xamarin_main + 880
	38  Slackord                            0x00000001012090fc main + 64
	39  dyld                                0x0000000186407f28 start + 2236
)
libc++abi: terminating due to uncaught exception of type NSException

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x101107490 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_dump_native_crash_info
	0x1010c02d8 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_handle_native_crash
	0x1012095ac - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : sigabrt_signal_handler.cold.1
	0x101106d50 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_runtime_setup_stat_profiler
	0x18678ea24 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x18675fc28 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x18666dae8 - /usr/lib/system/libsystem_c.dylib : abort
	0x186718b84 - /usr/lib/libc++abi.dylib : _ZN10__cxxabiv130__aligned_malloc_with_fallbackEm
	0x1867083d0 - /usr/lib/libc++abi.dylib : _ZL28demangling_terminate_handlerv
	0x1863dee58 - /usr/lib/libobjc.A.dylib : _ZL15_objc_terminatev
	0x186717f48 - /usr/lib/libc++abi.dylib : _ZSt11__terminatePFvvE
	0x18671ad34 - /usr/lib/libc++abi.dylib : __cxa_get_exception_ptr
	0x18671ace0 - /usr/lib/libc++abi.dylib : _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception
	0x1863d6130 - /usr/lib/libobjc.A.dylib : objc_exception_throw
	0x100d532d8 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : xamarin_process_managed_exception
	0x100d52e00 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : xamarin_process_managed_exception_gchandle
	0x100d52db0 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : xamarin_ftnptr_exception_handler
	0x1010bfaf8 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_handle_exception_internal
	0x1010be660 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_handle_exception
	0x1011175c0 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : interp_throw
	0x1011157f0 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : interp_throw_ex_general
	0x1011107d8 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_interp_exec_method
	0x1011082d8 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : interp_entry_from_trampoline
	0x100d25938 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : native_to_interp_trampoline
	0x1865b0400 - /usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x1865bebf8 - /usr/lib/system/libdispatch.dylib : _dispatch_main_queue_drain
	0x1865be848 - /usr/lib/system/libdispatch.dylib : _dispatch_main_queue_callback_4CF
	0x18687fbc4 - /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation : __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
	0x18683d344 - /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation : __CFRunLoopRun
	0x18683c428 - /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation : CFRunLoopRunSpecific
	0x190090df0 - /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox : RunCurrentEventLoopInMode
	0x190090c2c - /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox : ReceiveNextEventCommon
	0x190090984 - /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox : _BlockUntilNextEventMatchingListInModeWithFilter
	0x189a64908 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : _DPSNextEvent
	0x189a63aa4 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
	0x189a57f08 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication run]
	0x189a2f358 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : NSApplicationMain
	0x189c87b04 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : +[NSWindow _savedFrameFromString:]
	0x19deb8960 - /System/Library/PrivateFrameworks/UIKitMacHelper.framework/Versions/A/UIKitMacHelper : UINSApplicationMain
	0x1b20278e8 - /System/iOSSupport/System/Library/PrivateFrameworks/UIKitCore.framework/Versions/A/UIKitCore : UIApplicationMain
	0x100d3c5f4 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : xamarin_UIApplicationMain
	0x101117da0 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : do_icall
	0x101116624 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : do_icall_wrapper
	0x10110b04c - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_interp_exec_method
	0x101108c20 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : interp_runtime_invoke
	0x101051490 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_jit_runtime_invoke
	0x100ff1c70 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_runtime_invoke_checked
	0x100ff7fac - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_runtime_exec_main_checked
	0x1010a3f48 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : mono_jit_exec
	0x100d65970 - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : xamarin_main
	0x1012090fc - /Users/vertis/Downloads/mac-catalyst/Slackord.app/Contents/MacOS/Slackord : main
	0x186407f28 - /usr/lib/dyld : start

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x186728744):0x186728734  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x186728744  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x186728754  65 e0 ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  e........{...._.
0x186728764  c0 03 5f d6 70 0a 80 d2 01 10 00 d4 03 01 00 54  .._.p..........T

=================================================================
	Managed Stacktrace:
=================================================================
	 at <unknown> <0xffffffff>
	 at UIKit.UIApplication:xamarin_UIApplicationMain <0x0006c>
	 at UIKit.UIApplication:UIApplicationMain <0x00044>
	 at UIKit.UIApplication:Main <0x000f8>
	 at Slackord.Program:Main <0x00018>
	 at <Module>:runtime_invoke_direct_void_string[] <0x0004a>
	 at <unknown> <0x00000>
=================================================================
fish: Job 1, 'Slackord.app/Contents/MacOS/Sla…' terminated by signal SIGABRT (Abort)
```

**Comment by thomasloupe** [comment]
Noted, will have a look at this.
Should probably be catching the null exception.

In the meantime, make sure you are selecting the root folder as your import, which is likely what's causing the NullRef. 😃

**Comment by vertis** [comment]
@thomasloupe It finds all the files before it crashes, so I'd be surprised if it was a lack of selecting the root folder. I did have other problems where it couldn't find the `user.json` when I made this mistake

**Comment by thomasloupe** [comment]
Hey @vertis,

Apologies that you were having issues with this.
I am going to be removing Slackdump compatibility at this point. I know this isn't what you wanted to hear, but it appears that Slackdump and Slackord are _somewhat_ doing things a bit too differently at this point. It seems like some cases it works and some it does not. 

The best advice I can offer at this time is to ensure that Slackdump is using the same kind of JSON formatting as a typical Slack export does. I have seen some cases where `{`, which starts an object, a collection of key-value pairs and `[`, which starts an array, an ordered list of values are reversed in the JSON file, causing Slackord to crash immediately. I don't really have a workaround for this and don't plan to change the formatting in a way that would hinder the default Slack import.

I would, however, try to give it a go on Windows if you could, as the Mac version also has lots of bugs I'm just unable to get around at this point.
I'm sorry about that, and I will update the readme to reflect those changes.

Please do reach out to me directly via our community Discord if you continue to have issues and I will do my best to help!
